# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01b981cd276ad296a51b89cdc66b53d1b630696e10e44d0d9eb544679dded7abe5e08b980e47f3347e6c728545904d72e0fcd6bbcec9b05661005aa4e88df632

test:
  secret_key_base: c865810953bf0553b0c386c53a772c15b7bfab7c0d2f8b03f0e28833413ad8c8b0995004a74fdc0c7f478f058c67359fe2328f69ae9594d58c42b5d8e15d194d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
